/**
 * @fileoverview YouTube ClickBait Filter - Filtering Constants
 * Comprehensive lists of keywords and phrases used for content filtering.
 * 
 * This module exports arrays of clickbait words and phrases that are commonly
 * used in sensationalized YouTube titles. These constants are used by the
 * filtering algorithm to identify and remove clickbait content from user feeds.
 * 
 * Categories include:
 * - Alarmist and crisis language
 * - Sensationalized descriptors
 * - Emotional manipulation terms
 * - Exaggerated claims and superlatives
 * - Common clickbait phrases and patterns
 * 
 * @author Rory Glenn
 * @version 1.0.0
 * @since 2025-08-08
 */

// constants.js

/**
 * Array of words indicating negative, alarming, or sensationalized content.
 * These words are commonly used in clickbait titles to create urgency,
 * fear, or emotional responses. Titles containing these words may be
 * filtered based on user preferences.
 * 
 * @type {string[]}
 * @example
 * // Check if title contains clickbait words
 * const hasClickbait = CLICKBAIT_WORDS.some(word => 
 *   title.toLowerCase().includes(word)
 * );
 */
export const CLICKBAIT_WORDS = [
    'actually',
    'alarming',
    'anarchy',
    'bloodbath',
    'bombshell',
    'breakdown',
    'calamity',
    'carnage',
    'cataclysm',
    'catastrophe',
    'catastrophic',
    'chaos',
    'chaotic',
    'collapse',
    'confession',
    'conflict',
    'contagion',
    'crash',
    'crises',
    'crisis',
    'debacle',
    'debunked',
    'devastating',
    'disaster',
    'disastrous',
    'disturbing',
    'emergency',
    'epidemic',
    'exclusive',
    'explosive',
    'exposed',
    'frantic',
    'frenzy',
    'frightening',
    'hacks',
    'havoc',
    'horrific',
    'horrifying',
    'intense',
    'lifehack',
    'live:',
    'livestream:',
    'mayhem',
    'meltdown',
    'menacing',
    'mindblowing',
    'nightmarish',
    'ominous',
    'outbreak',
    'pandemic',
    'panic',
    'perilous',
    'plague',
    //   "pov -",
    //   "pov:",
    'revealed',
    'scandalous',
    'secrets',
    'shocking',
    'terrifying',
    'threatening',
    'tragic',
    'transformation',
    'turmoil',
    'unbelievable',
    'unprecedented',
    'unsettling',
    'unthinkable',
    'upheaval',
    'uproar',
    'urgent',
    'volatile',
    'warning',
    'worrisome',
    'wtf',
];

/**
 * Array of common clickbait phrases used to identify sensational headlines.
 * These phrases are frequently used in manipulative content designed to
 * generate clicks through curiosity gaps, false promises, or exaggerated claims.
 * 
 * @type {string[]}
 * @example
 * // Check if title contains clickbait phrases
 * const hasClickbaitPhrase = CLICKBAIT_PHRASES.some(phrase => 
 *   title.toLowerCase().includes(phrase)
 * );
 */
export const CLICKBAIT_PHRASES = [
    '1 simple trick',
    '10 things',
    '10 ways',
    '100 percent effective',
    '100 percent guaranteed',
    '100 percent risk free',
    '100% effective',
    '100% guaranteed',
    '100% risk free',
    '5 things',
    '5 ways',
    '99% of people',
    'a big secret',
    'a huge secret',
    'about to crack',
    'about to explode',
    'about to get',
    'act fast',
    'act now',
    'act quick',
    'act right now',
    'after this happened',
    'after watching this',
    'after what happened',
    'all hell',
    'all you need to know',
    'amazing secret',
    'and what happened next',
    'are ruining the',
    'are secretly',
    'became to crack',
    'become impossible',
    'before & after',
    'before and after',
    "before it's too late",
    'before its too late',
    'best kept secret',
    'biggest secret',
    'blew your mind',
    'blow your mind',
    'blows your mind',
    'boost your',
    'boosts your',
    'breaking news',
    'breaking story',
    'caught in the act',
    'caught on cam',
    'caught on camera',
    'caught red handed',
    'change everything',
    'changed everything',
    'changes everything',
    'cheat code',
    'click here',
    'click to see',
    'complete guide',
    'completely rethink',
    'completely wrong',
    'cure for',
    'dark reality',
    'destroying every',
    'destroying everything',
    'destroying your',
    'did you know',
    'didnt you know',
    'do not let this happen',
    'do not want you to',
    'doctors hate him',
    "don't let this happen",
    "don't want you to",
    'dont let this happen',
    'easy trick',
    'epic fail',
    'epic failure',
    'ever made',
    'everybody wants to',
    'everyone is',
    'everyone wants to',
    'experts dont want you to know',
    'extreme makeover',
    'fail compilation',
    'fails compilation',
    'first time ever',
    'for the first time',
    'game changer',
    'gets worse',
    'getting worse',
    'goes wrong',
    'going to crack',
    'gone viral',
    'gone wrong',
    'gonna crack',
    'gonna explode',
    'gonna get',
    'gonna make you',
    'gonna shock you',
    'government confirmed',
    'government confirms',
    'govt confirmed',
    'hack code',
    'hack ur',
    'hack your',
    'here is how',
    'here is what',
    'hidden agenda',
    'hidden hack',
    'hidden horror of',
    'hidden horrors of',
    'hidden truth',
    'hidden weapon',
    'how to get ahead',
    'how to get ahead of',
    'incredible secret',
    'is ruining the',
    'is secretly',
    'is this over',
    'is this the end',
    'jaw dropping',
    'jaw-dropping',
    'just dropped',
    'just got leaked',
    'just leaked',
    'just released',
    'life changing',
    'life hack',
    'life or death situation',
    'life-changing',
    'life-or-death situation',
    'limited time',
    'limited time only',
    'massive fail',
    'methods to',
    'mind blowing',
    'mind-blowing',
    'miracle hack',
    'miracle trick',
    'must see',
    'must watch',
    'never before',
    'never seen',
    'no one',
    'nobody is talking about',
    'nobody talks about',
    'nobody tells',
    'nobody wants',
    'of all time',
    'of the year',
    'offer ends',
    'one simple trick',
    'one thing',
    'one trick for',
    'one trick to',
    'only 1 percent of people',
    'only 1% of people',
    'only way to',
    'point of view:',
    'prepare to be amazed',
    'read before',
    'read this before',
    'real reason',
    'reason why',
    'rethink everything',
    'rethink ur life',
    'rethink your life',
    'ruining every',
    'ruining everything',
    'ruining your',
    'scam alert',
    'scientists hate him',
    'secret agenda',
    'secret hack',
    'secret of',
    'secret trick',
    'secret truth',
    'secret weapon',
    'simple trick',
    'snake oil',
    'starting to crack',
    'stunned the world',
    'the biggest',
    'the future of',
    'the one thing',
    'the only way to',
    'the real reason',
    'the reason why',
    'the truth about',
    'they lie to us',
    'they lie to you',
    'they lied to us',
    'they lied to you',
    'they tried to hide this',
    'things i wish i knew',
    'things i wish i knew before',
    'things u need to',
    "things you don't know",
    'things you dont know',
    'things you need to',
    'this is how',
    'this is over',
    'this is the end',
    'this is what',
    'this year',
    'ticking time bomb',
    'time bomb',
    'today only',
    'total game changer',
    'total makeover',
    'truth about',
    'u have to see this',
    'u need to',
    'ultimate guide',
    'ultimate secret',
    'unseen footage',
    'ur missing out',
    'viral hit',
    'viral sensation',
    'ways to',
    'weird trick',
    'weirdest thing',
    'went viral',
    'what happened next',
    'what happens next',
    'what most people',
    'what no one tells you',
    'what nobody tells you',
    "what they don't want you to know",
    'what they dont want you to know',
    'why all',
    'why are all',
    'why most people',
    'why nobody',
    'why u should',
    'why you should',
    'will change everything',
    'will make you',
    'will shock you',
    'you are missing out',
    'you got no idea',
    'you have no idea',
    'you have to see this',
    'you must see',
    'you must watch',
    'you need to',
    'you will not believe',
    "you won't believe",
    'you wont believe',
    'you would not believe',
    "you wouldn't believe",
    'you wouldnt believe',
    "you'll ever need",
    "you're missing out",
    'youll ever need',
    'your missing out',
];
